<?xml version="1.0" encoding="UTF-8"?>
<definitions targetNamespace="http://example.com/addService"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap"
>

	<types>
		<xsd:schema elementFormDefault="qualified">
			<xsd:element name="addRequest">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="a" type="xsd:double" />
						<xsd:element name="b" type="xsd:double" />
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>

			<xsd:element name="addResponse">
				<xsd:complexType>
					<xsd:element name="result" type="xsd:double" />
				</xsd:complexType>
			</xsd:element>
		</xsd:schema>
	</types>

	<message name="addRequestMessage">
		<part name="parameters" element="tns:addRequest" />
	</message>

	<message name="addResponseMessage">
		<part name="result" element="tns:addResponse" />
	</message>

	<portType name="AddServicePort">
		<operation name="add">
			<input message="tns:addRequestMessage" />
			<output message="tns:addResponseMessage" />
		</operation>
	</portType>

	<binding name="AddServiceBinding" type="tns:AddServicePort">
		<soap:binding transport="http://schemas.xmlsoap.org/soap/http"
		/>

		<operation name="add">
			<soap:operation soapAction="http://example.com/addService/add" />

			<input>
				<soap:body use="encoded" namespace="tns">
					<parameters />
				</soap:body>
			</input>

			<output>
				<soap:body use="encoded" namespace="tns">
					<result />
				</soap:body>
			</output>
		</operation>
	</binding>

	<service name="AddService">
		<port name="AddServicePort" binding="tns:AddServiceBinding">
			<soap:address location="http://localhost:3000/add" />
		</port>
	</service>

</definitions>